version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>
          no_output_timeout: 1h

  run-grakn-server:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-bin/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/simulation
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel build //...
      - run: bazel run @graknlabs_build_tools//unused_deps -- list

  test-end-to-end:
    machine: true
    working_directory: ~/simulation
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-grakn-server
      - run: bazel run //:simulation -- -d -k world
      - run: bazel test //agents/test/... --test_arg=localhost:48555 --test_output=all

workflows:
  version: 2
  simulation:
    jobs:
      - build
      - test-end-to-end:
          requires:
            - build
