version: 2.1
commands:
  install-bazel:
    steps:
      - run: |
          mkdir install
          cd install
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tool/bazelinstall/linux.sh
          bash ./linux.sh
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tool/bazelinstall/rbe.sh
          bash ./rbe.sh
          cd ..
          rm -rf install

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/simulation
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel build //...
      - run: bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list

  test-end-to-end:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/simulation
    steps:
      - install-bazel
      - checkout
      - run-grakn-server
      - run: bazel run //:simulation -- -d -k world
      - run: bazel test //agents/test/... --test_arg=localhost:48555 --test_output=all

workflows:
  version: 2
  simulation:
    jobs:
      - build
      - test-end-to-end:
          requires:
            - build
