build:
  correctness:
    test-comparison-grakn-background:
      machine: 16cpus-32gb
      image: graknlabs-ubuntu-20.04
      type: background
      timeout: "5h"
      command: |
        cat > grakn-core.service <<- EOM
        [Unit]
        Description=Grakn Core

        [Service]
        Type=simple
        ExecStart=/home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/grakn server
        Restart=on-failure
        RestartSec=10
        KillMode=process

        [Install]
        WantedBy=multi-user.target
        EOM

        sudo mv grakn-core.service /etc/systemd/system/

        bazel run //test:grakn-core-extractor-linux -- dist/grakn-core-all-linux
        cd ./dist/grakn-core-all-linux/

        sudo systemctl daemon-reload
        sudo systemctl start grakn-core
        export GRABL_EXPORT_TEST_COMPARISON_GRAKN_URI="${HOSTNAME}:1729"
      monitor: |
        sleep 10s
        tail -f -n +1 /home/grabl/$GRABL_REPO/dist/grakn-core-all-linux/server/logs/grakn.log
    test-comparison-neo4j-background:
      machine: 16cpus-32gb
      image: graknlabs-ubuntu-20.04
      type: background
      timeout: "5h"
      command: |
        sudo add-apt-repository -y ppa:openjdk-r/ppa
        curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update
        wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
        echo 'deb https://debian.neo4j.com stable 4.2' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        sudo apt-get update
        sudo apt-get install -y neo4j=1:4.2.0
        sudo update-java-alternatives --jre --set java-1.11.0-openjdk-amd64
        echo 'dbms.connector.bolt.listen_address=0.0.0.0:7687' | sudo tee -a /etc/neo4j/neo4j.conf
        echo 'dbms.security.auth_enabled=false' | sudo tee -a /etc/neo4j/neo4j.conf
        sudo systemctl restart neo4j
        export GRABL_EXPORT_TEST_COMPARISON_NEO4J_URI="${HOSTNAME}:7687"
      monitor: |
        journalctl -fu neo4j
    test-comparison-grakn-and-neo4j:
      image: graknlabs-ubuntu-20.04
      timeout: "5h"
      dependencies: [test-comparison-grakn-background, test-comparison-neo4j-background]
      command: |
        echo 'Trying to connect to Neo4j'
        attempt_counter=0
        max_attempts=50
        expected_exit_code=52
        until curl --output /dev/null --silent --head --fail $GRABL_EXPORT_TEST_COMPARISON_NEO4J_URI || [[ $? == $expected_exit_code ]]; do
            if [ ${attempt_counter} -eq ${max_attempts} ];then
              echo "Max attempts reached"
              exit 1
            fi

            echo '...'
            attempt_counter=$(($attempt_counter+1))
            sleep 3
        done
        bazel test //test:comparison-test \
          --test_output=all \
          --test_arg=--grakn-uri=$GRABL_EXPORT_TEST_COMPARISON_GRAKN_URI \
          --test_arg=--neo4j-uri=bolt://$GRABL_EXPORT_TEST_COMPARISON_NEO4J_URI
