build:
  performance:
    run-grakn:
      machine: graknlabs-ubuntu-20.04-long
      type: background
      timeout: "18000"
      script: |
        cd ..
        git clone https://github.com/graknlabs/grakn.git
        cd grakn
        bazel build //:assemble-linux-targz
        mkdir dist
        tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
        cd ./dist/grakn-core-all-linux/
        ./grakn server start -- \
          --tracing-uri $GRABL_TRACING_URI \
          --tracing-username $GRABL_OWNER \
          --tracing-access-token $GRABL_TOKEN
        export GRABL_EXPORT_PERFORMANCE_GRAKN_URI="${HOSTNAME}:48555"
    test-performance-big-grakn:
      machine: graknlabs-ubuntu-20.04-long
      timeout: "18000"
      dependencies: [run-grakn]
      script: |
        cat > config.yml << EOF
        agents:
          - name: "marriage"
            mode: "trace"
          - name: "personBirth"
            mode: "trace"
          - name: "ageUpdate"
            mode: "trace"
          - name: "parentship"
            mode: "off"
          - name: "relocation"
            mode: "off"
          - name: "company"
            mode: "off"
          - name: "employment"
            mode: "off"
          - name: "product"
            mode: "off"
          - name: "transaction"
            mode: "off"
          - name: "friendship"
            mode: "off"
        traceSampling:
          # Options: `"every"` for every K traces; `"log"` for logarithm with base N
          function: "every"
          arg: 3
        randomSeed: 1
        iterations: 30
        scaleFactor: 3
        databaseName: "world"
        EOF
        bazel run //:simulation -- \
          --database grakn \
          --database-uri $GRABL_EXPORT_PERFORMANCE_GRAKN_URI \
          --tracing-uri $GRABL_TRACING_URI \
          --org $GRABL_OWNER \
          --repo $GRABL_REPO \
          --commit $GRABL_COMMIT \
          --username $GRABL_OWNER \
          --api-token $GRABL_TOKEN \
          --config-file /home/grabl/simulation/config.yml
    run-neo4j:
      machine: graknlabs-ubuntu-20.04-long
      type: background
      timeout: "18000"
      script: |
        sudo add-apt-repository -y ppa:openjdk-r/ppa
        curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update
        wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
        echo 'deb https://debian.neo4j.com stable 4.1' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        sudo apt-get update
        sudo apt-get install -y neo4j=1:4.1.0
        sudo update-java-alternatives --jre --set java-1.11.0-openjdk-amd64
        echo 'dbms.connectors.default_listen_address=0.0.0.0' | sudo tee -a /etc/neo4j/neo4j.conf
        echo 'dbms.security.auth_enabled=false' | sudo tee -a /etc/neo4j/neo4j.conf
        ps aux | grep "org.neo4j.server" | awk '{print $2}' | xargs sudo kill -9 >/dev/null 2&>1 || true
        sudo neo4j start
        export GRABL_EXPORT_PERFORMANCE_NEO4J_URI="bolt://${HOSTNAME}:7687"
    test-performance-big-neo4j:
      machine: graknlabs-ubuntu-20.04-long
      dependencies: [run-neo4j]
      timeout: "18000"
      script: |
        cat > config.yml << EOF
        agents:
          - name: "marriage"
            mode: "trace"
          - name: "personBirth"
            mode: "trace"
          - name: "ageUpdate"
            mode: "trace"
          - name: "parentship"
            mode: "off"
          - name: "relocation"
            mode: "off"
          - name: "company"
            mode: "off"
          - name: "employment"
            mode: "off"
          - name: "product"
            mode: "off"
          - name: "transaction"
            mode: "off"
          - name: "friendship"
            mode: "off"
        traceSampling:
          function: "every"
          arg: 3
        randomSeed: 1
        iterations: 30
        scaleFactor: 3
        databaseName: "world"
        EOF
        bazel run //:simulation -- \
          --database neo4j \
          --database-uri $GRABL_EXPORT_PERFORMANCE_NEO4J_URI \
          --tracing-uri $GRABL_TRACING_URI \
          --org $GRABL_OWNER \
          --repo $GRABL_REPO \
          --commit $GRABL_COMMIT \
          --username $GRABL_OWNER) \
          --api-token $GRABL_TOKEN \
          --config-file /home/grabl/simulation/config.yml
    run-grakn-test:
      machine: graknlabs-ubuntu-20.04-long
      type: background
      timeout: "18000"
      script: |
        cd ..
        git clone https://github.com/graknlabs/grakn.git
        cd grakn
        bazel build //:assemble-linux-targz
        mkdir dist
        tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
        cd ./dist/grakn-core-all-linux/
        ./grakn server start -- \
          --tracing-uri $GRABL_TRACING_URI \
          --tracing-username $GRABL_OWNER \
          --tracing-access-token $GRABL_TOKEN
        export GRABL_EXPORT_TEST_GRAKN_URI="${HOSTNAME}:48555"
    run-neo4j-test:
      machine: graknlabs-ubuntu-20.04-long
      type: background
      timeout: "18000"
      script: |
        sudo add-apt-repository -y ppa:openjdk-r/ppa
        curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt-get update
        wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
        echo 'deb https://debian.neo4j.com stable 4.1' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
        sudo apt-get update
        sudo apt-get install -y neo4j=1:4.1.0
        sudo update-java-alternatives --jre --set java-1.11.0-openjdk-amd64
        echo 'dbms.connectors.default_listen_address=0.0.0.0' | sudo tee -a /etc/neo4j/neo4j.conf
        echo 'dbms.security.auth_enabled=false' | sudo tee -a /etc/neo4j/neo4j.conf
        ps aux | grep "org.neo4j.server" | awk '{print $2}' | xargs sudo kill -9 >/dev/null 2&>1 || true
        sudo neo4j start
        export GRABL_EXPORT_TEST_NEO4J_URI="bolt://${HOSTNAME}:7687"
    test-comparison-grakn-and-neo4j:
      machine: graknlabs-ubuntu-20.04-long
      timeout: "18000"
      dependencies: [run-grakn]
      script: |
        bazel test //test:simulation-test \
          --test_output=all \
          --test_arg=--grakn-uri=$GRABL_EXPORT_TEST_GRAKN_URI \
          --test_arg=--neo4j-uri=$GRABL_EXPORT_TEST_NEO4J_URI
