agents:
  # For each agent select a `mode`, `"run"` to run without tracing, `"trace"` to run with tracing, and "off" to not run at all
  - name: "marriage"
    mode: "trace"
  - name: "personBirth"
    mode: "trace"
  - name: "ageUpdate"
    mode: "trace"
#  - name: "parentship"
#    mode: "run"
#  - name: "relocation"
#    mode: "run"
#  - name: "company"
#    mode: "run"
#  - name: "employment"
#    mode: "run"
#  - name: "product"
#    mode: "run"
#  - name: "transaction"
#    mode: "run"
#  - name: "friendship"
#    mode: "run"

traceSampling:
  # Options: `"every"` for every K traces; `"log"` for logarithm with base N
  function: "every"
  arg: 3

randomSeed: 1
iterations: 30
scaleFactor: 3
databaseName: "world"
