agents:
  # For each agent select a `mode`, `"run"` to run without tracing, `"trace"` to run with tracing, any other input to
  # not run or trace
  - name: "MarriageAgent"
    mode: "run"
  - name: "PersonBirthAgent"
    mode: "trace"
  - name: "AgeUpdateAgent"
    mode: "trace"
  - name: "ParentshipAgent"
    mode: "trace"
  - name: "RelocationAgent"
    mode: "trace"
  - name: "CompanyAgent"
    mode: "trace"
  - name: "EmploymentAgent"
    mode: "trace"
  - name: "ProductAgent"
    mode: "trace"
  - name: "TransactionAgent"
    mode: "trace"
  - name: "FriendshipAgent"
    mode: "trace"
#samplingFunction:
#  name: "every"
#  arg: 5
iterationTraceSampling: "logarithmic_iterations_base_10"